# Generated by Django 2.2 on 2021-04-05 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('address1', models.CharField(max_length=128, verbose_name='기본 주소')),
                ('address2', models.CharField(max_length=128, verbose_name='상세 주소')),
                ('phone', models.CharField(max_length=16, verbose_name='유선전화')),
                ('_phone', models.CharField(max_length=16, verbose_name='유선전화 w/o 하이픈')),
                ('mobile_phone', models.CharField(max_length=16, verbose_name='휴대전화')),
                ('_mobile_phone', models.CharField(max_length=16, verbose_name='휴대전화 w/o 하이픈')),
                ('birth', models.DateField(null=True, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('zh_CN', '中文(简体)'), ('en', 'English')], default='ko', max_length=5)),
                ('is_staff', models.BooleanField(default=False, verbose_name='어드민 여부')),
                ('is_dormant', models.BooleanField(default=False, verbose_name='휴면 계정 여부')),
                ('joined_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일시')),
                ('is_certified', models.BooleanField(default=False, verbose_name='본인인증 여부')),
                ('cert_imp_uid', models.CharField(max_length=64, verbose_name='본인인증 imp_uid')),
                ('cert_unique_key', models.CharField(max_length=88, verbose_name='본인인증 unique_key')),
                ('cert_unique_in_site', models.CharField(max_length=64, verbose_name='본인인증 unique_in_site')),
                ('certified_time', models.DateTimeField(null=True, verbose_name='인증일시')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
